### PR TITLE
Improve deoplete racer source

### PR DESCRIPTION
**Pull request by Shougo**
It improves the deoplete racer source.
Could you merge it?

### CODE REVIEW

**Comment by phildawes** [comment]
Done, thanks. @Shougo Would you like to have commit access on this project? (I sent a request a while ago but I don't think it got to you)

**Comment by Shougo** [comment]
> Would you like to have commit access on this project? (I sent a request a while ago but I don't think it got to you)

Thank you!
Yes, I want to have the commit access if possible.
This project seems one maintainer and you are busy for Racer project.
Fortunately, I know the VimL :-)

**Comment by phildawes** [comment]
I updated the invitation in github. Did you receive it?

**Comment by Shougo** [comment]
@phildawes 

Unfortunately, I have not get the invitation.
What's the needed action for me?

I think you just to add the collaborator for me...

**Comment by phildawes** [comment]
@Shougo according to the github page for vim-racer there is 1 pending invitation to Shougo. it says:

"Invitations are sent via email and can be accepted at https://github.com/racer-rust", so maybe point your browser there and see if an invitation pops up?

(I can't see a way to remove the invitation so I can send it again. I was hoping editing and updating it would cause a re-send). Is there anything in your github notifications about it?

**Comment by Shougo** [comment]
Thank you!
I don't get the email but I can acccept the invitation from https://github.com/racer-rust.
I have joined.

**Pull request merged**
