### PR TITLE
Fixes a bug where racer doesn't detect cargo crates.

### PR DESCRIPTION
**Pull request by norcalli**
The file needs to be in the proper directory to be able to pull the correct
Cargo.toml file. This is not ideal, but sufficient.

### CODE REVIEW

**Comment by phildawes** [comment]
Hi @norcalli 
Thanks for this, I think this can be fixed by passing a separate parameter with the tempfile rather than writing the tempfile in the same directory. See here: https://github.com/phildawes/racer/issues/447#issuecomment-165373334

**Comment by norcalli** [comment]
Ah sounds good. I can update the pull request with that syntax.

**Comment by Shougo** [comment]
@norcalli This pull request has the conflict.
Can you fix it?

**Comment by Shougo** [comment]
@norcalli Ping.

**Comment by norcalli** [comment]
Sorry, I recently graduated and started a new job. Been a bit busy. From what I remember, I tried the syntax suggested by phil, but it didn't work for some reason, and I didn't manage to debug it before I stopped working on it. However, my approach did work, so I've updated the pull request with that syntax, which should work, though it is less than optimal.

However, I can also just close this if that isn't acceptable, because I'm not sure when I'll have time to test it again.

**Comment by Shougo** [comment]
OK, thanks.

**Pull request merged**
